image:  
  - Ubuntu2004
  - macos
  - Visual Studio 2019
#platform:
#  - x86
#  - x64
test_script:
  - cmd: cd build && ctest -C Debug
for:
  -
    matrix:
      only:
      - image: Ubuntu2004  
    environment:
      matrix:
        - COMPILER: GCC
        - COMPILER: Clang
    configuration:
      - Release
    clone_folder: ~/source
    install:
    - sudo apt-get update
    #- sudo apt-get install ccache
    - sudo apt-get --yes install python3-pip
    - python3 --version
    - python3 -m pip install --user conan
    build_script:
      - cmake -S ~/source -B ./build
      - cmake --build ./build
  -
    matrix:
      only:
      - image: macos      
    environment:
      matrix:
        - COMPILER: GCC
        - COMPILER: Clang
    configuration:
      - Release
    clone_folder: ~/source
    install:
      python -m pip install --user conan
    build_script:
      - cmake -S ~/source -B ./build
      - cmake --build ./build
  -
    matrix:
      only:
      - image: Visual Studio 2019
    configuration:
      - Debug
      - Release
    environment:
      PYTHON: "C:\\Python38-x64\\python.exe"
    clone_folder: c:\projects\source
    build_script:
        - cmd: |
            set PATH=%PATH%;C:\Users\appveyor\AppData\Roaming\Python\Python38\Scripts
            "%PYTHON%" -m pip install --user conan
            cmake -S c:\projects\source -B ./build -G "Visual Studio 16 2019" -DCMAKE_BUILD_TYPE:STRING=Release
            cmake --build ./build --config "Release"
